### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by profclark**
:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `master` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `master` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `master`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

Subscribed: @Wuestefeld1

### CODE REVIEW

**Review by profclark — COMMENTED** [review]
Hi Dirck,

Will you be submitting planning documents for this project? I will change your grade in GitHub if you submit this soon.

**Comment by Wuestefeld1** [comment]
I submitted it 2 weeks ago. The day you changed the due date I turned it
in. I was already done. I also emailed you.

**Comment by Wuestefeld1** [comment]
[image: image.png]See it is there, labeled plan as you asked. 10 days ago

**Comment by profclark** [comment]
Hi Dirck,

I see the index.html and 2 CSS files you submitted, which look like this in a browser ...

image

This looks nice, but it is not the site planning document I need. The site plan describes an overview of the project you will develop along with goals an other related information. I provided a reference document in Blackboard and discussed it several times in class. It be found here ... [https://github.com/scsu-clarkm1-fall-2020-csc443/project-1-personal-website-profclark/tree/master/plan](https://github.com/scsu-clarkm1-fall-2020-csc443/project-1-personal-website-profclark/tree/master/plan).

 If you submitted something else I never received it. I double checked your GitHub repo, Blackboard and email. The link to the screenshot (the image you referenced in your previous comment) is broken so I cannot see the image you are referencing.

Please let me know if you have questions and try and get the site planning document to me as soon as possible.

**Comment by Wuestefeld1** [comment]
No I updated them. I deleted those and as they say went back to the drawing
board. At first I thought I could put in the bootstrap style syntax with
what I was already working on, but it only made it a mess and harder. So I
made a blank and used your methods to create them with that being what I am
looking to achieve. Please take another look, they have the same name, but
the code is 100% different in the index and other HTML files.  I started
with the grid as I stated i the plan. Which requires me also to start with
a blank wall.

**Comment by Wuestefeld1** [comment]
My SSD in my computer is too old and causing it to crash. So for a week, I
had no computer again. During that time I completed my prototype augmented
reality sand table which I have tied to my research project for my
capstone. I am hoping to have the entire project done by next Friday. Which
will give me an extra 30-40 hours a week to put into finishing the website.
The AR sandtable was my primary goal, with it working now I only need to
wrap up the research and papers. I'm doing it solo, but working on it until
morning. Which help me get a lot done. I have borrowed a computer and am
catching up on many things. I am also taking data mining fun, but I don't
need it for the degree. So your class will my new primary focus.
I hope you are not upset or insulted about how I have divided my
attention on my different projects. Most do like hearing that theirs even
while being worked on is not worked on as much as another.

**Comment by profclark** [comment]
Hi Dirck,

Once again, sorry for all the confusion with the planning document. As you know, we are squared away with that. I also sent you an email asking about the design document (no rush, just didn't want to miss it). 

I am definitely not insulted. I understand that you have obligations for other classes. I more concerned about making sure you have the info/guidance you need so you can get stuff done when you have time.

Once I get your design document here (see my note in email about merging to master), I will review and post feedback.

Michael

**Pull request merged**
